# .github/workflows/test-workflow.yml
name: Simple Test Workflow

on:
  push:
    branches:
      - main # This workflow runs on every push to the 'main' branch

jobs:
  hello_world_job:
    runs-on: macos-latest
    steps:
    - name: Say Hello
      run: echo "Hello from GitHub Actions!"